---
- hosts: ws
  become: yes
  user: root
  gather_facts: True
  ignore_errors:
  vars: 
    user_name: petit2334
  
  vars_files:
    - variables.yaml
  tasks:
    - name: Check the uptime
      command: "{{my_command}}"
    - name: Creating directory on our system
      file: 
        state: directory
        name: "{{folders}}"
    - name: Creating user
      user:
        name: "{{user_name}}"
    - name: Read data
      debug:
        var: "{{user_name}}"
    - name: Check the kernel version
      shell: uname -r
      register: kernel_output
    - name: Read data
      debug:
        var: kernel_output.stdout
    - name: Checking the number of cpu
      shell: nproc
      register: number_cpu
    - name: Read Data
      debug:
        var: number_cpu.stdout
    